[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
targetPort = 3000
framework = "vite"

[[redirects]]
  from = "/foo"
  to = "/bar"
  status = 302
  force = true

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"
